- name: Deploy Chime .NET8.0 API
  hosts: all
  become: yes
  tasks:


    - name: Update package index
      apt: 
        update_cache: yes


    - name: Install .NET8.0 and Caddy
      apt:
        name:
          - dotnet8
          - caddy
        state: present


    - name: Copy API app files from monorepo to VM instance
      copy: 
        src: ./ChimeCore/
        dest: /home/azureuser/ChimeCore
        owner: azureuser
        group: azureuser
        mode: '0755'


    - name: Install dependencies
      command: dotnet restore
      args: 
        chdir: /home/azureuser/ChimeCore


    - name: Configure Caddy reverse proxy for automatic HTTPS
      shell: printf "{{ AZURE_VM_IPV4_ADDR }}.nip.io {\n\treverse_proxy localhost:5001\n}" > /etc/caddy/Caddyfile


    - name: Clear the Publish subdirectory if it exists
      ansible.builtin.file:
        path: /home/azureuser/ChimeCore/publish
        state: absent


    - name: Kill old app processes if it exists
      shell: fuser -k 5001/tcp || true


    - name: Publish app
      command: dotnet publish -c Release -o ./publish
      args: 
        chdir: /home/azureuser/ChimeCore


    - name: Run caddy HTTPS proxy
      shell: caddy run --environ --config /etc/caddy/Caddyfile
      async: 0
      poll: 0


    - name: Run app
      shell: dotnet ./publish/ChimeCore.dll > /tmp/chime.log 2>&1 &
      args: 
        chdir: /home/azureuser/ChimeCore
      async: 0
      poll: 0


    - name: Check app is running
      wait_for:
        host: localhost
        port: 5001


    # - name: Check Caddy is running
    #   wait_for:
    #     host: localhost
    #     port: 443
