- name: Deploy Chime .NET8.0 API
  hosts: all
  become: yes
  tasks:
    - name: Update package index
      apt: 
        update_cache: yes

    - name: Install .NET8.0
      apt:
        name:
          - dotnet8
        state: present

    - name: Copy API app files from monorepo to VM instance
      copy: 
        src: ./ChimeCore/
        dest: /home/azureuser/ChimeCore
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Install dependencies
      command: dotnet restore
      args: 
        chdir: /home/azureuser/ChimeCore

    - name: Publish app
      command: dotnet publish -c Release -o ./publish
      args: 
        chdir: /home/azureuser/ChimeCore

    - name: Create cronjob to start app
      cron:
        name: Start app on boot
        special_time: reboot
        job: nohup dotnet /home/azureuser/ChimeCore/publish/ChimeCore.dll &

    - name: Run app
      shell: nohup dotnet ./publish/ChimeCore.dll &
      args: 
        chdir: /home/azureuser/ChimeCore
      async: 0
      poll: 0

    - name: Check app is running
      shell: ps ux | grep dotnet | grep -v grep
      register: result
      until: result.stdout | length > 0
      retries: 5
      delay: 5
